force-app/main/default/objects/External_Service_Params__mdt/External_Service_Params__mdt.object-meta.xml
<CustomObject>
    <description>PGP-0009 : Create Custom Metadata to store all Param for each services</description>
    <label>External Service Params</label>
    <pluralLabel>External Service Params</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_Service_Params__mdt/fields/Is_Required_Encoding__c.field-meta.xml
<CustomField>
    <fullName>Is_Required_Encoding__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PGP-0009 : Value should be encoded if this field value if True</description>
    <label>Is Required Encoding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Service_Params__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>PGP-0009 : Store key value of selected types</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Service_Params__mdt/fields/Key_Value_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Key_Value_Prefix__c</fullName>
    <description>PGP-0009 : Stores key value prefix. Ex : Add Basic&quot; in Authorization header</description>
    <label>Key Value Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Service_Params__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PGP-0009 : Store types of each request</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endpoint</fullName>
                <default>true</default>
                <label>Endpoint</label>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Method</fullName>
            </value>
            <value>
                <fullName>Param</fullName>
            </value>
            <value>
                <fullName>Timeout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Service_Params__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>PGP-0009 : Store value of keys</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/selectors/ExternalServiceParamsSelector.cls
/**
 * @description       : 
 * @author            : salesforce
 * @group             : gaurp
 * @last modified on  : 04-02-2025
 * @last modified by  : salesforce
**/
public with sharing class ExternalServiceParamsSelector extends fflib_SObjectSelector implements IExternalServiceParamsSelector {
    public static IExternalServiceParamsSelector newInstance(){
        return (IExternalServiceParamsSelector) Application.selector.newInstance(External_Service_Params__mdt.sObjectType);
    }
    public Schema.SObjectType getSObjectType(){
        return External_Service_Params__mdt.sObjectType;
    }
    public List<schema.SObjectField> getSObjectFieldList(){
        return new List<schema.SObjectField>{
            External_Service_Params__mdt.Id,
            External_Service_Params__mdt.MasterLabel,
            External_Service_Params__mdt.DeveloperName,
            External_Service_Params__mdt.Key__c,
            External_Service_Params__mdt.Value__c,
            External_Service_Params__mdt.Type__c,
            External_Service_Params__mdt.Is_Required_Encoding__c,
            External_Service_Params__mdt.Key_Value_Prefix__c
        };
    }
    public List<External_Service_Params__mdt> getExternalServiceParamsConfiguration(String serviceName){       
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.setCondition('MasterLabel = :serviceName');
        return (List<External_Service_Params__mdt>) Database.query(queryFactory.toSOQL());
    }
}