force-app/main/default/objects/Evaluation__c/Evaluation__c.object-meta.xml
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>EVAL-{0000}</displayFormat>
        <label>Evaluation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evaluation_Component__c/Evaluation_Component__c.object-meta.xml
<CustomObject>
    <label>Evaluation Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluation Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluation_Component__c/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <label>Evaluation</label>
    <referenceTo>Evaluation__c</referenceTo>
    <relationshipLabel>Evaluation</relationshipLabel>
    <relationshipName>Evaluation_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Evaluation_Component__c/fields/Image_Path__c.field-meta.xml
<CustomField>
    <fullName>Image_Path__c</fullName>
    <formula>CASE(Type__c,
&apos;Labs/Bloodwork&apos;, &apos;LabResults.png&apos;, 
&apos;Cardiac Clearance&apos;, &apos;HeartEvaluation.png&apos;,
&apos;Psychosocial Evaluation&apos;, &apos;Psyco.png&apos;,
&apos;Palliative Evaluation&apos;, &apos;PallativeEvaluation.png&apos;,
&apos;Financial Evaluation&apos;, &apos;Financial.png&apos;,
&apos;Dental Clearance&apos;, &apos;DentalClearance.png&apos;,
&apos;Cancer Screening&apos;, &apos;CancerScreening.png&apos;,
&apos;Diagnostic Imaging&apos;, &apos;DiagnosticImage.png&apos;,&apos;&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluation_Component__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evaluation_Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labs/Bloodwork</fullName>
            </value>
            <value>
                <fullName>Diagnostic Imaging</fullName>
            </value>
            <value>
                <fullName>Cardiac Clearance</fullName>
            </value>
            <value>
                <fullName>Dental Clearance</fullName>
            </value>
            <value>
                <fullName>Psychosocial Evaluation</fullName>
            </value>
            <value>
                <fullName>Palliative Evaluation</fullName>
            </value>
            <value>
                <fullName>Cancer Screening</fullName>
            </value>
            <value>
                <fullName>Financial Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PatientEvaluationComponents.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : gaurp
 * @last modified on  : 04-02-2025
 * @last modified by  : salesforce
**/
public with sharing class PatientEvaluationComponents {
 @AuraEnabled(Cacheable=true)
 public static List<Evaluation_Component__c> getEvaluationComponents(String recordId){
    try {
        return [
            SELECT
                Id, 
                Name, 
                Evaluation__c, 
                Status__c, 
                Type__c, 
                Completion_Date__c, 
                Due_Date__c, 
                Notes__c,
                Image_Path__c
            FROM
                Evaluation_Component__c
            WHERE
                Evaluation__c =: recordId
            WITH SECURITY_ENFORCED
            
        ];
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
 }
}