force-app/main/default/objects/External_Vendor_API_Keys__c/External_Vendor_API_Keys__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>PG-00002 - Custom Setting to store an external vendor API keys.</description>
    <label>External Vendor API Keys</label>
</CustomObject>

force-app/main/default/objects/External_Vendor_API_Keys__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>PG-00002 - API Keys for the external vendor.</description>
    <inlineHelpText>API Keys for the external vendor.</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Vendor_API_Keys__c/fields/API_Key_Param_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Key_Param_Name__c</fullName>
    <description>PGP-0008 : Store API Key field name</description>
    <label>API Key Param Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Vendor_API_Keys__c/fields/External_Vendor__c.field-meta.xml
<CustomField>
    <fullName>External_Vendor__c</fullName>
    <description>PG-00002- Name of external vendor</description>
    <inlineHelpText>External vendor name</inlineHelpText>
    <label>External Vendor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/External_Vendor_API_Keys__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>PGP-0008 : Setting a named credential value for HttpRequest</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Vendor_API_Keys__c/fields/Time_Out__c.field-meta.xml
<CustomField>
    <fullName>Time_Out__c</fullName>
    <defaultValue>2000</defaultValue>
    <description>PGP-0008 : Set HttpRequest Timeout Value</description>
    <label>Time Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/tests/classes/unit/services/ExternalVendorsIntegrationServiceTest.cls
/**
 * @description       : 
 * @author            : salesforce
 * @group             : 
 * @last modified on  : 02-19-2025
 * @last modified by  : salesforce
**/
@isTest
public with sharing class ExternalVendorsIntegrationServiceTest {
    @IsTest
    private static void validateExtervalVendorWhenPass() {
        External_Vendor_API_Keys__c externalVendorAPIKey = createExternalVendorAPIKeyrecord();
        Test.startTest();
            Map<String, String> externalVendorIntegrations = ExternalVendorsIntegrationService.getExternalServiceResult('Reverse Geocoding');
        Test.stopTest();
        System.assertEquals(true, externalVendorIntegrations.size()>0, 'External Vendor Integration should not be null');
    }
    private static External_Vendor_API_Keys__c createExternalVendorAPIKeyrecord(){
        External_Vendor_API_Keys__c externalVendorAPIKey = new External_Vendor_API_Keys__c();
        externalVendorAPIKey.Name = 'Reverse Geocoding';
        externalVendorAPIKey.API_Key__c = '4f5a3d7a72aa42c187e549f8c74c12c7';
        externalVendorAPIKey.Named_Credential__c = 'callout:Reverse_Geocoding';
        externalVendorAPIKey.External_Vendor__c = 'Reverse Geocoding';
        externalVendorAPIKey.Time_Out__c = 2000;
        externalVendorAPIKey.API_Key_Param_Name__c = 'key';
        insert externalVendorAPIKey;
        return externalVendorAPIKey;
    }
}